name: diet_time
description: Premium healthy meal subscription application.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^3.0.0
  flutter_secure_storage: ^10.0.0
  flutter_svg: ^2.2.0
  go_router: ^17.0.0
  intl: ^0.20.2
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/logo/
    - assets/pattern/
    - assets/images/
    - assets/fonts/
